### ISSUE TITLE
`--help` and `--version` throw an error

### ISSUE THREAD

**Issue by paulmenzel** [galaxyproject/ansible-galaxy#11]
$ ansible-galaxy --help
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

Options:
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
  --version      show program's version number and exit
ERROR! Missing required action
$ echo $?
5

**Comment by paulmenzel** [comment]
The same goes for `--version`.

```
$ ansible-galaxy --version
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

Options:
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
  --version      show program's version number and exit
ERROR! Missing required action
```

Debian 8.3 (jessie) with Ansible 2.0.1.0-1~bpo8+1 from [Debian Backports](http://backports.debian.org) is used.

**Comment by mvdbeek** [comment]
hi @paulmenzel, I think you should report this over at https://github.com/ansible/ansible,
this repository contains a role for installing galaxy servers, that bear no relation with ansible-galaxy (despite the confusing name).

**Comment by paulmenzel** [comment]
@mvdbeek, true. [Done.](https://github.com/ansible/ansible/issues/14856). Sorry for the noise.
