### ISSUE TITLE
`__galaxy_user_group` is undefined if `galaxy_manage_paths` is not enabled

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/ansible-galaxy#137]
However, the systemd service unit template assumes that it is. We should move the tasks that collect and set those variables to an always-run task include file between the `galaxy_create_user` and `galaxy_manage_paths` tasks.

**Comment by hexylena** [comment]
xref https://help.galaxyproject.org/t/galaxy-user-group-is-undefined/6600/2
