### ISSUE TITLE
Option to install additional python packages into virtual environment

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/ansible-galaxy#140]
There could be a list variable `galaxy_additional_venv_packages` to specify additional python packages to install into the galaxy virtual environment.  My use case is that Galaxy Australia wants to install a package 'total-perspective-vortex' into galaxy's virtual environment.  The most logical time to install this than after the venv is created and before galaxy is restarted.

**Comment by natefoo** [comment]
Fixed in #150, thanks @cat-bro!
