### ISSUE TITLE
galaxy_config_perms set incorrectly in default variables?

### ISSUE THREAD

**Issue by Slugger70** [galaxyproject/ansible-galaxy#158]
I tried to run the newest ansible recently for a new server. 

In the default variables `galaxy_config_perms` is set to `0640` which then gives permissions of `-rw-r-----` on `galaxy.yml`. It's owner and group is set to `root:root` when using privilege sep and the layout: `root-dir`.

If the galaxy user is set to "galaxy" then it cannot read it's own config file.. :(

Should the default setting for `galaxy_conf_perms` be `0644`?

**Comment by hexylena** [comment]
Shouldn't be 4 in the last place, don't want anyone reading the secrets. But root:root could maybe be root:galaxy or so?

**Comment by Slugger70** [comment]
That makes sense. I'll do a PR.

**Comment by Slugger70** [comment]
It looks as though the group for the static config files not specified as 0644 need to be set to the galaxy_user so that it can read the file.
