### ISSUE TITLE
Why preventing mutable configurations from being overwritten?

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/ansible-galaxy#179]
https://github.com/galaxyproject/ansible-galaxy/blob/2b89a7c8759d417198d65d74ab6aaeade08b744f/tasks/mutable_setup.yml#L11

If I understand correctly, to change a mutable configuration using this role, you'll have first to delete the current config from the host before replaying the playbook ?

**Comment by hexylena** [comment]
Yes, this is correct. The mutable directory, once created, is more or less "maintained" by a lot of different galaxy processes. Manually changing the files is possible, but if we overwrote the file on deploy, we'd be constantly losing changes Galaxy is trying to make to those files (e.g. installation of genomes/etc)
