### ISSUE TITLE
Automatic addition of `themes_config_file_by_host: {}` disables themes

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/ansible-galaxy#200]
After updating this role to version 0.10.19 our themes have disappeared, along with the option to select a theme in user preferences.

In our galaxy.yml file we have

```
    themes_config_file: /mnt/galaxy/config/themes_conf.yml
    themes_config_file_by_host: {}
```

We can get our themes back by commenting out `themes_config_file_by_host`.

**Comment by mira-miracoli** [comment]
@hexylena I am not sure if there is a possibility to omit these keys when default.yml is not a jinja template
