### ISSUE TITLE
Problems with ansible 2.3.0.0

### ISSUE THREAD

**Issue by mapa17** [galaxyproject/ansible-galaxy#21]
Hello, 

i have difficulties running ansible version 2.3.0.0.
Should the playbook in the README file work with that ansible version?

I got permission errors when during the posgres installation, but was able to resolve this modifying the playbook 

instead of 
`galaxyproject.postgresql`

writing
```
-role: galaxyproject.postgresql
  become: yes
```

but now faile the task

TASK [natefoo.postgresql_objects : Create and drop users]

with
```

fatal: [10.60.64.239]: FAILED! => {
    "failed": true, 
    "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/tmp/ansible-tmp-1496834871.61-164298282349901/': Operation not permitted\nchown: changing ownership of '/tmp/ansible-tmp-1496834871.61-164298282349901/postgresql_user.py': Operation not permitted\n). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"
```
'

Any ideas?

**Comment by mapa17** [comment]
As mentioned in the ansible documentation [becoming-an-unprivileged-user](https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user)

this could be resolved by enabling pipelinging in the ansible.cfg configuration file (if it does not exists, just creat on in the playbook directory)

ansible.cfg
```
[ssh_connection]
pipelining=True
```

**Comment by bgruening** [comment]
Ha, good to know! Thanks for reporting back!
