### ISSUE TITLE
uwsgi support

### ISSUE THREAD

**Issue by dometto** [galaxyproject/ansible-galaxy#210]
The 'Best practices' section in the Readme recommends using `uwsgi`, but it is currently not even installed as part of the Galaxy python requirements. So support for `uwsgi` in this role is not working, barring manual hacks. Perhaps references to uwsgi should be removed from the documentation, or support for installing it automatically should be added?

(In addition, it seems to me that the 'Best practices' section could use some updating -- the strategy outlined there does not work without also explicitly enabling support for `systemd` with `mule`. Is this still really the best practice?)

**Comment by hexylena** [comment]
uWSGI is no longer possible to use, references to it should be removed completely.

no it is not current best practice, you're right it needs an update.
