### ISSUE TITLE
errordocs image files

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/ansible-galaxy#23]
@natefoo while I was trying to fix a bug in GalaxyKickStart, I incidentally came to the [errordocs.yml](https://github.com/galaxyproject/ansible-galaxy/blob/master/tasks/errordocs.yml) file.
I guess that the files
    - content_bg.png
    - error_message_icon.png
    - masthead_bg.png
are supposed to be sourced from the templates directory but I cannot find them there

**Comment by natefoo** [comment]
@drosofff You should be able to find them under the [files/errordocs/](https://github.com/galaxyproject/ansible-galaxy/tree/master/files/errordocs) directory.
