### ISSUE TITLE
Trouble signing up / logging into galaxy via Github

### ISSUE THREAD

**Issue by someara** [galaxyproject/ansible-galaxy#26]
I'm having trouble signing up / logging into galaxy via Github... I had a defunct email as the primary address in my Github profile. I've since fixed that and revoked/reauthorized galaxy, but it feels like there's something cached somewhere.

jlozadad in IRC suggested I create an issue in the ansible-galaxy repo.

If this isn't the correct place, please point me in the right direction.

Thanks in advance,

-s

**Comment by erasche** [comment]
Hi @someara, do you mean RedHat's "Ansible Galaxy" service? I.e. http://galaxy.ansible.com/

This is an unrelated repo with a similar name. You're probably looking for https://github.com/ansible/galaxy/
