### ISSUE TITLE
Backward compatibility with older galaxy releases (18.05)

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/ansible-galaxy#57]
Hi, I could not say since when, but the playbook errors with galaxy release_18.05, due to the node install/ node version step. You can see an exemple [here](https://travis-ci.org/ARTbio/ansible-galaxy/builds/485322171#L693).

The only thing I can ensure is that it was still working at this [commit](https://github.com/galaxyproject/ansible-galaxy/commit/2298c56b399769889a832f5d640370d8cf26bfa6), about 2 months ago

**Comment by natefoo** [comment]
Sorry about this, we'll be better about backwards compatibility going forward. Unfortunately at this stage we're not going to fix it for 18.05, but 18.09 and forward should be ok.
