### ISSUE TITLE
Node version cannot be changed

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/ansible-galaxy#61]
Because we use the `command` module to install node with nodeenv, and because we determine whether that task needs to run by checking for the existence of `{{ galaxy_venv_dir }}/bin/npm`, once installed, the node version will not change even if `galaxy_node_version` is changed.

**Comment by dannon** [comment]
xref the logic common_startup uses: https://github.com/galaxyproject/galaxy/blob/dev/scripts/common_startup.sh#L232

and https://github.com/galaxyproject/galaxy/pull/7357, which should be useful.

**Comment by natefoo** [comment]
Fixed in #83
