### ISSUE TITLE
Tool installation via webinterface fails with permission errors

### ISSUE THREAD

**Issue by maikknebel** [galaxyproject/ansible-galaxy#73]
When i try to install tools from toolshed via the webinterface, i get permission denied errors for **../server/database**, **../server/tools** and  **../server/tool-data**. If i change the permissions of the directorys by hand, it will crash a bit later anyways.

I used the recommended settings to install my instance with galaxy_separate_privileges: true and have the privileged user **gxpriv** and the normal user **galaxy**. My instance is started via supervisorctl and by the user gxpriv.
Folder <galaxy_install_folder>/server/database has 0755 and gxpriv:galaxy
Folder <galaxy_install_folder>/server/tools has 0755 and gxpriv:galaxy
Folder <galaxy_install_folder>/server/tool-data has 0755 and gxpriv:galaxy

```
Error cloning repository: Command '['hg', 'clone', '-r', u'11', u'https://toolshed.g2.bx.psu.edu/repos/devteam/blast_datatypes', u'/srv/galaxy/server/database/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/blast_datatypes/01b38f20197e/blast_datatypes']' returned non-zero exit status 255 Output was: abort: Permission denied: '/srv/galaxy/server/database/shed_tools' 
```
Any idea how to fix this or what the root of the problem could be?

**Comment by maikknebel** [comment]
@AliNemat After a lot of testing and lost time i decided to just drop the privileg separation completly. Recently we droped the baremetal installation completly and are now using the docker images.

**Comment by AliNemat** [comment]
@maikknebel Thank you for your response.
